### ISSUE TITLE
Scaling issues on smaller screen

### ISSUE THREAD

**Issue by pbjorklund** [aspel/pobfrontend#1]
Got an old mac mini still running, so figured I'd give your package a test on a pretty old version of osx.

Looked through all the commits on the fork and nothing fishy stood out to me (note: was not 100% thorough)

![image](https://user-images.githubusercontent.com/290776/70801809-2c208600-1db0-11ea-998e-7fce1ec599e6.png)

It works, but some wonky sizing on a small monitor

![image](https://user-images.githubusercontent.com/290776/70801816-30e53a00-1db0-11ea-9e63-ae222c41a636.png)

![image](https://user-images.githubusercontent.com/290776/70801818-32aefd80-1db0-11ea-9a42-c17dd8b83044.png)

**Comment by aspel** [comment]
I see.
There is a pobWrapper.sh file inside PathOfBuilding.app/Contents/MacOS/
you can try to add a font size into it.
```
#!/bin/bash

cd "${0%/*}"
./PathOfBuilding -2
```

**Comment by pbjorklund** [comment]
I don't even need the mac port 😂 Just wanted to share.
