### ISSUE TITLE
Build for iOS

### ISSUE THREAD

**Issue by vinczemarton** [aspel/pobfrontend#11]
There is currently no iOS app that is PoB compatible. Is it theorethically possible to build this to iOS? Are there any bigger roadblocks like touchscreen support or zoom that would make it unusable without an UI rework?

**Comment by aspel** [comment]
I am not expert in iOS, but as I understand you should install apps via AppStore. 
Even if I recompile app to ARM CPU, it should somehow be uploaded to AppStore.
