### ISSUE TITLE
CTD when importing from Pastebin

### ISSUE THREAD

**Issue by farmboy0** [aspel/pobfrontend#6]
Importing this pastebin results in crash to desktop:
https://pastebin.com/KHDty33K

And the following error message:
PANIC: unprotected error in call to Lua API (error in error handling)

I'm using the latest release.

**Comment by sliiser** [comment]
Running into the same issue with a different pastebin (https://pastebin.com/auFwETyM). Crashes from both pastebin link and copy-paste code itself.

EDIT:

Works when using community fork from https://github.com/bernhardfritz/pobfrontend/releases/tag/PathOfBuilding

Found it from #5

**Comment by farmboy0** [comment]
Thats what I am using now too.
