### ISSUE TITLE
Can't import from pastebin link

### ISSUE THREAD

**Issue by binarydepth** [aspel/pobfrontend#8]
I get this error:

PANIC: unprotected error in call to Lua API (error in error handling)

LINK

https://pastebin.com/YEj6N7a1

**Comment by binarydepth** [comment]
I installed both the Lua packages in Kubuntu 20.04.1 64 bit

**Comment by crmaxx** [comment]
I have same issue on start on OSX version from `releases` (or builded by myself)
```
λ aspel_pobfrontend/PathOfBuilding.app/Contents/MacOS master ✗ ./PathOfBuilding
PANIC: unprotected error in call to Lua API (error in error handling)
```
